controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: POST

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: POST

products_list:
    path: /products-list
    controller: App\Controller\ProductsController::productsList
    methods: GET

add_product:
    path: /add-product
    controller: App\Controller\AdminController::addProduct
    methods: POST