controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: POST

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: POST

log_admin:
    path: /logadmin
    controller: App\Controller\AdminLoginController::logAdmin

products_list:
    path: /products-list
    controller: App\Controller\ProductsController::productsList
    methods: GET

single_product:
    path: /single-product/{id}
    controller: App\Controller\ProductsController::singleProduct
    methods: GET

add_product:
    path: /add-product
    controller: App\Controller\AdminController::addProduct
    methods: POST

add_to_cart:
    path: /add-to-cart/{id}
    controller: App\Controller\CartController::addToCart
    methods: POST

get_cart:
    path: /get-cart/{id}
    controller: App\Controller\CartController::getCart
    methods: GET

app_logout:
    path: /logout
    methods: GET