controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

products_list:
    path: /products-list
    controller: App\Controller\ProductsController::productsList
    methods: GET