controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: POST

account_activation:
    path: /account-activation
    controller: App\Controller\RegistrationController::accountActivation
    methods: POST

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: POST

log_admin:
    path: /logadmin
    controller: App\Controller\AdminLoginController::logAdmin

products_list:
    path: /products-list
    controller: App\Controller\ProductsController::productsList
    methods: GET

single_product:
    path: /single-product/{id}
    controller: App\Controller\ProductsController::singleProduct
    methods: GET

add_product:
    path: /add-product
    controller: App\Controller\AdminController::addProduct
    methods: POST

add_to_cart:
    path: /add-to-cart/{id}
    controller: App\Controller\CartController::addToCart
    methods: POST

get_cart:
    path: /get-cart/{id}
    controller: App\Controller\CartController::getCart
    methods: GET

get_storage:
    path: /get-storage
    controller: App\Controller\CartController::getStorage
    methods: GET

pay:
    path: /pay
    controller: App\Controller\PaymentController::pay
    methods: POST

order:
    path: /order
    controller: App\Controller\OrderController::order
    methods: POST

get_order:
    path: /get-order/{id}
    controller: App\Controller\OrderController::getOrder
    methods: GET

add_address:
    path: /add-address
    controller: App\Controller\AddressController::addAddress
    methods: POST

get_address:
    path: /get-address
    controller: App\Controller\AddressController::getAddress
    methods: GET

app_logout:
    path: /logout
    methods: GET