controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: POST

account_activation:
    path: /account-activation
    controller: App\Controller\RegistrationController::accountActivation
    methods: POST

token_activation_again:
    path: /token-activation-again
    controller: App\Controller\RegistrationController::resendTokenActivation
    methods: POST

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: POST

log_admin:
    path: /logadmin
    controller: App\Controller\AdminLoginController::logAdmin

products_list:
    path: /products-list
    controller: App\Controller\ProductsController::productsList
    methods: GET

single_product:
    path: /single-product/{id}
    controller: App\Controller\ProductsController::singleProduct
    methods: GET

plateformes_list:
    path: /plateformes-list
    controller: App\Controller\ProductsController::plateformesList
    methods: GET

genres_list:
    path: /genres-list
    controller: App\Controller\ProductsController::genresList
    methods: GET

vote_test:
    path: /vote-test/{id}
    controller: App\Controller\ProductsController::voteTest
    methods: POST

submit_test:
    path: /submit-test
    controller: App\Controller\TestController::submitTest
    methods: POST

user_tests:
    path: /user-tests
    controller: App\Controller\TestController::userTests
    methods: GET

get_test:
    path: /get-test/{id}
    controller: App\Controller\TestController::getTest
    methods: GET

update_test:
    path: /update-test/{id}
    controller: App\Controller\TestController::updateTest
    methods: PUT

add_product:
    path: /add-product
    controller: App\Controller\AdminController::addProduct
    methods: POST

add_to_cart:
    path: /add-to-cart/{id}
    controller: App\Controller\CartController::addToCart
    methods: POST

get_cart:
    path: /get-cart/{id}
    controller: App\Controller\CartController::getCart
    methods: GET

update_cart:
    path: /update-cart
    controller: App\Controller\CartController::updateCart
    methods: PUT

delete_item:
    path: /delete-item
    controller: App\Controller\CartController::deleteItem
    methods: DELETE

get_storage:
    path: /get-storage
    controller: App\Controller\CartController::getStorage
    methods: GET

pay:
    path: /pay
    controller: App\Controller\PaymentController::pay
    methods: POST

order:
    path: /order
    controller: App\Controller\OrderController::order
    methods: POST

get_order:
    path: /get-order/{id}
    controller: App\Controller\OrderController::getOrder
    methods: GET

order_historic:
    path: /order-historic
    controller: App\Controller\OrderController::orderHistoric
    methods: GET

single_order_historic:
    path: /single-order-historic/{reference}
    controller: App\Controller\OrderController::singleOrderHistoric
    methods: GET

add_address:
    path: /add-address
    controller: App\Controller\AddressController::addAddress
    methods: POST

get_address:
    path: /get-address
    controller: App\Controller\AddressController::getAddress
    methods: GET

change_address:
    path: /change-address
    controller: App\Controller\AddressController::changeAddress
    methods: PUT

delete_address:
    path: /delete-address
    controller: App\Controller\AddressController::deleteAddress
    methods: DELETE

change_mail:
    path: /change-mail
    controller: App\Controller\ParametersController::changeMail
    methods: POST

check_mail:
    path: /check-mail
    controller: App\Controller\ParametersController::checkMail
    methods: POST

change_password:
    path: /change-password
    controller: App\Controller\ParametersController::changePassword
    methods: POST

change_pseudo:
    path: /change-pseudo
    controller: App\Controller\ParametersController::changePseudo
    methods: POST

upload_user_image:
    path: /upload-user-image
    controller: App\Controller\ParametersController::uploadImage
    methods: POST

get_user_data:
    path: /get-user-data
    controller: App\Controller\ParametersController::getUserData
    methods: GET

app_logout:
    path: /logout
    methods: GET